### ISSUE TITLE
how to kill a session or set timeout? 

### ISSUE THREAD

**Issue by sjqzhang** [maxlaverse/reverse-shell#4]
how to kill a session ? 

if some command run always in a session?  for example : tail -f xxx.log

how can i kill the session or set timeout ?

**Comment by maxlaverse** [comment]
Hi @sjqzhang!
The client you are using to connect to the `agent` should support trapping `ctrl+c`.

If you use `netcat` for example, after having starting the `tail` command, you can press `ctrl+v`, then `ctrl+c` and `enter` to have `tail` exit, but keepng the connection to the agent open
